### ISSUE TITLE
Errors for only one tracker

### ISSUE THREAD

**Issue by absywabsy** [fsamareanu/deluge_to_rtorrent#3]
Hi,

Any idea why this is happening with only a specific tracker? Other trackers are fine:

```Traceback (most recent call last):
  File "/home/username//bin/chtor", line 11, in <module>
    load_entry_point('pyrocore', 'console_scripts', 'chtor')()
  File "/home/username/.local/pyroscope/src/pyrocore/scripts/chtor.py", line 311, in run
    MetafileChanger().run()
  File "/home/username/.local/pyroscope/src/pyrocore/scripts/base.py", line 268, in run
    self.mainloop()
  File "/home/username/.local/pyroscope/src/pyrocore/scripts/chtor.py", line 247, in mainloop
    metafile.add_fast_resume(metainfo, datadir)
  File "/home/username/.local/pyroscope/src/pyrocore/util/metafile.py", line 330, in add_fast_resume
    filepath = os.path.join(datapath, fmt.to_utf8(filepath.strip(os.sep)))
  File "/home/username/.local/pyroscope/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 8: ordinal not in range(128)
/bin/mv: cannot stat '/tmp/deluge-to-rt-IUzkoBgICY/c3b9c9eaeb17b27bee2a2007a485e8af66a69c5c-no-resume.torrent': No such file or directory
Invalid config parameter for $trackerX_deluge_ratio, asuming localratio

ERROR    While calling d.custom.set('c3b9c9eaeb17b27bee2a2007a485e8af66a69c5c', 'deluge_ratio', '0.000'): Unknown hash for d.custom.set(c3b9c9eaeb17b27bee2a2007a485e8af66a69c5c) @ /home/username/.config/rtorrent/socket
realpath: 'ERROR    While calling d.get_base_path('\''c3b9c9eaeb17b27bee2a2007a485e8af66a69c5c'\''): Unknown hash for d.get_base_path(c3b9c9eaeb17b27bee2a2007a485e8af66a69c5c) @ /home/username/.config/rtorrent/socket': No such file or directory
An error has occuTRACKERNAME
$rtorrent_torrentdir is ERROR    While calling d.get_base_path('c3b9c9eaeb17b27bee2a2007a485e8af66a69c5c'): Unknown hash for d.get_base_path(c3b9c9eaeb17b27bee2a2007a485e8af66a69c5c) @ /home/username/.config/rtorrent/socket
Actual torrent dir is /home/username/files/delugesyncremote/TORRENT NAME
Torrent state is ERROR    While calling d.state('c3b9c9eaeb17b27bee2a2007a485e8af66a69c5c'): Unknown hash for d.state(c3b9c9eaeb17b27bee2a2007a485e8af66a69c5c) @ /home/username/.config/rtorrent/socket
Attempting to repair, sequence is 1/8
Repair iteration sequence is 1/8
ERROR    While calling d.stop('c3b9c9eaeb17b27bee2a2007a485e8af66a69c5c'): Unknown hash for d.stop(c3b9c9eaeb17b27bee2a2007a485e8af66a69c5c) @ /home/username/.config/rtorrent/socket
ERROR    While calling d.directory.set('c3b9c9eaeb17b27bee2a2007a485e8af66a69c5c', '/home/username/files/delugesyncremote'): Unknown hash for d.directory.set(c3b9c9eaeb17b27bee2a2007a485e8af66a69c5c) @ /home/username/.config/rtorrent/socket
ERROR    While calling d.check_hash('c3b9c9eaeb17b27bee2a2007a485e8af66a69c5c'): Unknown hash for d.check_hash(c3b9c9eaeb17b27bee2a2007a485e8af66a69c5c) @ /home/username/.config/rtorrent/socket
ERROR    While calling d.save_full_session('c3b9c9eaeb17b27bee2a2007a485e8af66a69c5c'): Unknown hash for d.save_full_session(c3b9c9eaeb17b27bee2a2007a485e8af66a69c5c) @ /home/username/.config/rtorrent/socket
ERROR    While calling d.custom1.set('c3b9c9eaeb17b27bee2a2007a485e8af66a69c5c', 'TRACKERNAME_404_SHORT'): Unknown hash for d.custom1.set(c3b9c9eaeb17b27bee2a2007a485e8af66a69c5c) @ /home/username/.config/rtorrent/socket
ERROR    While calling d.start('c3b9c9eaeb17b27bee2a2007a485e8af66a69c5c'): Unknown hash for d.start(c3b9c9eaeb17b27bee2a2007a485e8af66a69c5c) @ /home/username/.config/rtorrent/socket```

**Comment by fsamareanu** [comment]
Can you set this in your script:


export LANG=en_US.UTF-8
